author = "Linux Gaming Central"
description = ""
menu_position = "Center"
font_color = "WHITE"
cursor_color = "BLUE"
background_scroll_speed = "OFF"
color_shift_speed = "OFF"
bgm_track = "None"
logo_selection = "None"
background_selection = "ps2_background.png"
font_selection = "ps2_font.ttf"
sfx_pack = "ps2_sfx"
