author = "Ashthorne Gaming"
description = "Theme based on the original Xbox dashboard. Background video taken from yesfull man's Xbox Dashboard for Wallpaper Engine. Xbox Dashboard font provided by DLEDeviant."
menu_position = "TopRight"
font_color = "WHITE"
cursor_color = "YELLOW"
cursor_style = "TEXT"
cursor_blink_speed = "OFF"
cursor_transition_speed = "OFF"
background_scroll_speed = "OFF"
color_shift_speed = "OFF"
bgm_track = "xbox_bgm.ogg"
logo_selection = "logo.png"
background_selection = "xbox_background.mp4"
font_selection = "xbox_menu.ttf"
sfx_pack = "xbox_original_sfx"