author = "Linux Gaming Central"
description = ""
menu_position = "BottomLeft"
font_color = "WHITE"
cursor_color = "RED"
cursor_style = "TEXT"
cursor_blink_speed = "OFF"
cursor_transition_speed = "OFF"
background_scroll_speed = "OFF"
color_shift_speed = "OFF"
bgm_track = "None"
logo_selection = "None"
background_selection = "ps1_background.png"
font_selection = "ps1_font.ttf"
sfx_pack = "ps1_sfx"
